### ISSUE TITLE
Type of data could have "long"?

### ISSUE THREAD

**Issue by Wx-Will** [seatrix/Keil-Array-Visualization#1]
The application is very good! But I found a small problem when I use this app. The problem is if I get an array with 1024 bytes, and set the type of data as "int", the data in this figure should have 1024 points. However, the figure just has 256 points so that I cannot draw the complete curve.
Could you fix the problem? Thank you very much!

**Comment by seatrix** [comment]
Int is represented by 4 bytes in this software, so 1024 bytes represents 1024/4 = 256 int data. If 1024 ints are required, the data volume is 4096 bytes

**Comment by HANS007GZ** [comment]
hello...  guys...
how can I contact you? 
Is there any email?

in the project of your fork, there is a legal risk involved, I hope you remove it --> XHQ_Demo

hopefully you can contact someone who has fork this project and delete it
@wx812 wx812 / XHQ_Demo

@seatrix @wx812
