### ISSUE TITLE
软件各种报错无法使用

### ISSUE THREAD

**Issue by meijialun** [seatrix/Keil-Array-Visualization#2]
![Snipaste_2020-11-19_11-36-41](https://user-images.githubusercontent.com/5047912/99618079-a72bfb00-2a5b-11eb-81e5-ceb60b3ca185.png)
![Snipaste_2020-11-19_11-36-52](https://user-images.githubusercontent.com/5047912/99618094-ac894580-2a5b-11eb-83d2-40e45997a4d4.png)

**Comment by seatrix** [comment]
增加读取大小试试
